services:
  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\DcGeneral\UpdateDataDefinition:
    tags:
      - name: kernel.event_listener
        event: dc-general.factory.build-data-definition
        method: addMcwFields
        priority: -5000

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\GetOptionsBridge:
    arguments:
      - '@event_dispatcher'
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.get-options
        method: executeEvent

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\TinyMce:
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.get-tiny-mce
        method: executeEvent

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\DatePicker:
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.get-date-picker
        method: executeEvent

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\ColorPicker:
    arguments:
      - '@=service(''contao.framework'').getAdapter(''Contao\\Image'')'
      - '@=service(''contao.framework'').getAdapter(''Contao\\StringUtil'')'
      - "@contao.translation.translator"
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.get-color-picker
        method: executeEvent

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\DcaPickerWizard:
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.get-dca-picker-wizard
        method: executeEvent

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Mcw\CreateWidget:
    tags:
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.create-widget
        method: createWidgetContao
      - name: kernel.event_listener
        event: contao-community-lliance.multi-column-wizard-bundle.create-widget
        method: createWidgetDcGeneral
