services:
  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Contao\ExecutePostActions:
    public: true
    arguments:
      - '@event_dispatcher'

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Contao\InitializeSystem:
    public: true

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Contao\LoadDataContainer:
    public: true

  ContaoCommunityAlliance\MultiColumnWizardBundle\EventListener\Contao\ParseTemplate:
    public: true
